version: 2.1

executors:
  flutter-executor:
    docker:
      - image: cirrusci/flutter:stable
    working_directory: ~/project

jobs:
  build:
    executor: flutter-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Run tests
          command: flutter test
      - run:
          name: Build APK
          command: flutter build apk --release

workflows:
  build_and_test:
    jobs:
      - build